# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  schedule:
    - cron: '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
jobs:
  test:
    if: ${{ env.LAST_COMMIT != github.GITHUB_SHA }}
    runs-on: ubuntu-latest
    name: Publish Logseq graph
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - uses: logseq/publish-spa@v0.1.0
      - name: add a nojekyll file # to make sure asset paths are correctly identified
        run: touch $GITHUB_WORKSPACE/www/.nojekyll
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
